# Clean Centralised Variable Engine Dashboard
replicaCount: 3

global:
  tier: production

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

# Dynamic Networking Service Configurations
service:
  type: ClusterIP
  port: 80

# Isolated Native Database Parameters
localPostgres:
  database: app_production_db
  username: platform_sre_user
  password: VaultSecureClusterPass77
