apiVersion: v1
kind: Secret
metadata:
  name: platform-db-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL2RiX2FkbWluOlNlY3VyZVBsYXRmb3JtUGFzczk5QGRiLWNsdXN0ZXIuaW50ZXJuYWw6NTQzMi9jb3JlX3Byb2Q=
