apiVersion: v1
kind: Pod
metadata:
  name: platform-storage-audit-pod
spec:
  containers:
    - name: test-container
      image: nginx:alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: test-storage
          mountPath: /var/log/nginx
  volumes:
    - name: test-storage
      persistentVolumeClaim:
        claimName: platform-production-pvc
